### ISSUE TITLE
Try to use provided classfication model for detection_and_classification but kernel size is even

### ISSUE THREAD

**Issue by Langhalsdino** [AvsThiago/DeepBee-source#3]
I tried to use `/DeepBee-source/src/DeepBee/software/detection_and_classification.py` on Ubunut 16.04 with the provided [classification.h5](classification's model). During inference the `kernel_size` seems to be even and not odd. Is there another model is should use or is the model definition incorrect?

```bash
Using Theano backend.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "detection_and_classification.py", line 395, in <module>
    main()
  File "detection_and_classification.py", line 387, in main
    create_detections()
  File "detection_and_classification.py", line 342, in create_detections
    m_border = load_model(dic_model['border'])
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/layers/convolutional.py", line 847, in call
    dilation_rate=self.dilation_rate)
  File "/home/mr-t/anaconda3/envs/deepbee/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 2258, in conv2d_transpose
    raise ValueError('In `Conv2DTranspose`, with padding mode `same`, '
ValueError: In `Conv2DTranspose`, with padding mode `same`, even kernel sizes are not supported with Theano. You can set `kernel_size` to an odd number.

```

**Comment by AvsThiago** [comment]
Could you try changing your backend from Theano to TensorFlow?

https://stackoverflow.com/questions/43327464/how-to-make-keras-use-tensorflow-backend-in-anaconda

**Comment by Langhalsdino** [comment]
using `export KERAS_BACKEND=tensorflow` helps. Just FYI, i tested it with TF 1.14.0
